typedef struct SChar {
    char* name;
} Character;

Character characters[] = {
    (Character) { "エメ" },
    (Character) { "ジゼル" },
    (Character) { "ジョルジュ" },
    (Character) { "ディディエ" },
    (Character) { "ネリー" },
    (Character) { "ハビ" },
    (Character) { "ベステア" },
    (Character) { "ポーリーン" },
    (Character) { "マリーア" },
    (Character) { "ミシェル" },
    (Character) { "メル" },
    (Character) { "モルガーナ" },
    (Character) { "ヤコポ" },
    (Character) { "ユキマサ" },
    (Character) { "三章白髪" },
    (Character) { "二章白髪" },
    (Character) { "回想女中" },
    (Character) { "大人ミシェル" },
    (Character) { "女中" },
    (Character) { "女中回想" },
    (Character) { "幼ミシェル" },
    (Character) { "狂気" },
    (Character) { "獣" },
    (Character) { "獣2" },
    (Character) { "白髪" },
    (Character) { "過去ネリー" },
    (Character) { "過去ポーリーン" },
    (Character) { "過去マリーア" },
    (Character) { "過去メル" },
    (Character) { "過去ヤコポ" },
    (Character) { "過去ユキマサ" },
};
